### ISSUE TITLE
Issue with Calculating CAGR

### ISSUE THREAD

**Issue by ericbrown** [fja05680/pinkfish#1]
I think there's a bug in the code used to call the cagr calculation on line 424 in the statistics.py file.

Currently, it reads:

```python
cagr = annual_return_rate(dbal['close'][-1] + dbal['cash'][-1],capital, start, end)
```

This is adding the ending balance to each other for the "end_balance".  I believe it should read:

```python
cagr = annual_return_rate(dbal['cash'][-1],capital, start, end)
```

**Comment by ericbrown** [comment]
Clarification - 

It looks like it should be 

```python
cagr = annual_return_rate(dbal['close'][-1],capital, start, end)
```

**Comment by fja05680** [comment]
Eric,
The formula appears to be correct as is.  "dbal" probably isn't named very well because it doesn't actually contain a total daily balance.  Instead, it contains the high, low, close, shares, and cash.  In order to calculate the end balance for the day, you need to multiply shares*close then add the cash.  The cash is not the total, it's the cash not invested.  Looking over this, I realize there are some related problems here with dbal though.  In the "Golden Cross" example, the shares are not subtracted on a sale, but the cash is recalculated.  If I corrected this, it would then expose a bug in plot.py "plot_equity_curve()" which only uses the shares and close values.  As it is, the bugs cancel one another out.  I need to fix this, and likely many other bugs.  My intent is to write some more examples so these bugs can be discovered.  Thanks for checking out pinkfish.

Farrell

**Comment by ericbrown** [comment]
Yeah - I can take care of it.
