### ISSUE TITLE
Idea: Adding multiple stocks and re-balance each week.

### ISSUE THREAD

**Issue by scorpio155** [fja05680/pinkfish#16]
Thanks for creating this simple to use framework. I have tested the framework for an Index with csv data I had and it worked well. I do see you have an example for portfolio of data which you are re balancing every month.

Could we use the new feature (portfolio) to rebalance a basket of stocks each week?
https://teddykoker.com/2019/05/momentum-strategy-from-stocks-on-the-move-in-python/

**Comment by scorpio155** [comment]
I was reading another code and Saw follow-trend (multiple securities) Sorry for creating the issue. Let me read up more and test to understand how it works.

**Comment by fja05680** [comment]
Hi,

Thanks for checking out Pinkfish.  Please be sure to git pull, since I
merge some significant changes last night.
On your question.  Yes, you can rebalance every week.  You can add calendar
indicators to a dataframe to do the rebalance on any weekday you wish, see
"sell-in-may-and-go-away" example.  Look at the portfolio example for a
backet of stocks.  I briefly looked at your website, and i'll check it out
more later.
I see you are also a fan of Andreas Clenow.  If I had his latest book when
I started writing Pinkfish I may have not done it.  I just couldn't find
any information
about how to get started and the toy examples were a poor guide.

Please let me know how I can help, or any suggestions for improvement.  I
wrote Pinkfish as a single stock/ETF back tester.  The portfolio and
shorting
capabilities are new additions, which I haven't done much with yet, besides
the examples in github.

Farrell

**Comment by fja05680** [comment]
https://github.com/fja05680/pinkfish/blob/master/pinkfish/calendar.py

calendar
---------
Adds calendar columns to a dataframe
dotw: day of the week with Monday=0, Sunday=6
dotm: day of the month as 1,2,...
doty: day of the year as 1,2, ...
month: month as January=1,...,December=12
first_dotw: first trading day of the week
last_dotw: last trading day of the week
first_dotm: first trading day of the month
last_dotm: last trading day of the month
first_doty: first trading day of the year
last_doty: last trading day of the year

**Comment by scorpio155** [comment]
Thanks a lot Farrell. The framework is really good, appreciate it that you coded it. I am learning python and trying to understand the way you have used oops concept and also made is simple to debug if compared to backtrader.

I do follow momentum investing and am interested in testing more, so was looking for frameworks to try it out. Its been a month to learn and test :)

I used backtrader as well. The site link I provided is not mine, I found it and was testing using backtrader. I will surely reach out and will be testing a portfolio with pinkfish. For now no recommendations.

Andreas books have been great and he has shared the full code for retail investors to learn as well. Along with your code, its simple to test a few strategies on the index. Example - I tested the golden cross on a India index NSE500 and it under performed the buy and hold :)

-Ashish

**Comment by fja05680** [comment]
Ashish,

Thank you for your kind words.  Congratulations on your first pinkfish
program.  The golden cross is probably the most well known long term
trading strategy for indexes, but not the best.  Both the momentum and
especially the sma-percent-band are better.  Try it out with the
sma-percent-band when you get a chance.  The problem with the golden-cross
is that the trade is made when the averages cross so you have no idea what
the trade price is going to be.  The other algorithms current price (not
averages) to determine the trade timing.  When analyzing backtest results,
I put greater emphasis on the drawdown and the ratios (sharpe and
sortino).  The annual return rate should be viewed in light of the other
metrics since it isn't rick adjusted.

Farrell

**Comment by scorpio155** [comment]
Hi Farrell,

Yes reducing the drawdown and time in drawdown will make the strategy much useful. Thanks again for the pointers and I did try out the SMA bands and it surely is much better than the Golden Cross. I am also working with the India top 500 market cap index and I used the below strategy on Nifty500

     Buy "CLOSE above EMA 5, RSI > 65, ADX > 25", Sell "Close below EMA 5

This resulted in a better profit than buy and hold for Nifty500, the returns were really poor on the SPY :)

I did look at the calendar and portfolio examples, trying to see how I can combine the tools here for multiple stocks. Example the trend following example does use multiple stocks, but was not able to see how I can add the buy and sell using that.

Example fixed portfolio of 10 stocks, we will need a ranking system to limit stocks, so we always have atleast 10 stocks. If you do get a chance and could put such an example will be helpful.

I will also work to understand the code better and see if I am able to do the same and share the example :)

Once again, thanks for sharing pinkfish.

Attached is the Nifty500 index data.
[NIFTY500.zip](https://github.com/fja05680/pinkfish/files/4842534/NIFTY500.zip)

**Comment by fja05680** [comment]
Ashish,

I'm glad you are having success using pinkfish.  It's an eye opener to see
what really works and what doesn't.  May I suggest that you look at trying
to determine what are the best values to use for your algorithm?  I have
many examples of how to write an optimizer.  My method, which shouldn't
result in overfitting the data, involves trying each technical indicator in
turn, and after deciding which are the best values individually, use those
values for the overall algorithm.  For example, write an optimizer that
uses only EMA.  Then another that uses EMA and RSI, fixing EMA to the value
determined from last optimization.  Then use EMA and ADX.  Finally, test
the entire algorithm.  In this case, indicators couldn't be tested
individually because only EMA is used for the Sell.  If you are able to
determine that an indicator adds little value then eliminate it.  The fewer
indicators and less complicated the algorithm, the less likely you are
overfitting the data.

I plan to write a S&P500 ETF sector ranker soon.  That should assist you
with what you are trying to achieve.

cheers,
Farrell
