### ISSUE TITLE
Can we buy at open and sell at close same candlestick?

### ISSUE THREAD

**Issue by tombohub** [fja05680/pinkfish#22]
Hello,
I am exploring a lot of backtesting libraries and after many hours it seems to me that none that I tried can buy at candlestick Open, close or sell at same candlestick Close. 
Before I start going trough examples, is it possible? 
Buy at candlestick Open, sell or close at same candlestick Close?

Thanks 

P.S. I saw you wrote this library for the exact same reason. I am just a bit frustrated now, just want confirmation to ease my mind

**Comment by fja05680** [comment]
Yes, that's the initial reason for the existence of pinkfish.  The reason you can't easily do it in other libraries is because most if not all of the Python backtesting libraries are event driven and deliver OHLC data and then you place orders against that which are executed starting the next trading day.  Pinkfish doesn't use an ordering system.  You can buy and sell when ever you wish.  I have just uploaded a simple example:

buy-open-sell-close

"On the first trading day of each week, buy on the open, then sell on the close "

**Comment by tombohub** [comment]
Very good, thanks!

**Comment by tombohub** [comment]
Sorry to bother you, but I think this kind of trading causes some warnings.
I tested golden cross example and it doesn't cause warnings.
So must be something regarding buying and selling on same candlestick and Zero 0.

```bash
/home/tomo/.local/share/virtualenvs/stock-trading-GXBc2mJL/src/pinkfish/pinkfish/statistics.py:522: RuntimeWarning: invalid value encountered in long_scalars
  stats['pct_profitable_years'] = (pc > 0).sum() / len(pc) * 100
/home/tomo/.local/share/virtualenvs/stock-trading-GXBc2mJL/lib/python3.8/site-packages/numpy/lib/function_base.py:380: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)
/home/tomo/.local/share/virtualenvs/stock-trading-GXBc2mJL/lib/python3.8/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
```

**Comment by fja05680** [comment]
When you get the data from yahoo get all of it, or at least several years, you should control your trading timeframe with the start and end variables.  I noticed in your code spinet that you were only getting 1 month.  Some indicators need many days before they become valid.  I believe the error you are seeing is caused by not having enough data.

**Comment by tombohub** [comment]
yes, that's it, it doesn't have warnings if I fetch longer period

**Comment by lorrp1** [comment]
@fja05680 hello, 
>              # rebalance portfolio
>                 for symbol, weight in weights.items():
>                     self.portfolio.adjust_percent(date, close[symbol], weights[symbol], symbol, row)
>             # record daily balance
>             self.portfolio.record_daily_balance(date, row)

id like to re-balance at opening price each day using the portfolio, but im not able to get the open from the row of self.ts, 
which is like this:
`
Index=Timestamp('2010-05-03 00:00:00'), SPY_high=97.39431739645367, SPY_low=96.19988653526296, SPY_close=97.12799072265624,` so without the SPY_open 

the run is the same taken from one of the example using portfolio  
`def run(self):
        self.portfolio = pf.Portfolio()
        self.ts = self.portfolio.fetch_timeseries(
            self.symbols.values(), self.start, self.end, use_cache=self.use_cache)
        
                # add calendar columns
        self.ts = self.portfolio.calendar(self.ts)
        
        self.ts, self.start = self.portfolio.finalize_timeseries(self.ts, self.start)
        
        self.portfolio.init_trade_logs(self.ts, self.capital, self.margin)

        self._algo()
`

**Comment by fja05680** [comment]
Hello, use get_prices(self, row, fields) to get the prices.  In examples/double-7s-portfolio/strategy.py _algo()
            p = self.portfolio.get_prices(row,
                fields=['close', 'regime', period_high_field, period_low_field, 'vola'])

Now you can use p[symbol]['close'].  You can add 'open' to your list of fields.

**Comment by lorrp1** [comment]
@fja05680 Hello, i tried like that before but i was getting an error and then i checked the row, there isnt at all the SPY_open column in the row so im getting that error

**Comment by fja05680** [comment]
I see.  In the portfolio fetchtime series function, you need to set the
field parameter to include open, like this, field= ['open', 'high', 'low',
'close'].  I'm trying to remember why I left out open by default.  I think
it was because it's typically not used by any of the technical analysis
functions.  I may include it back in by default though.  For now setting
the field will get what you want.

**Comment by fja05680** [comment]
Correction:fields not field.  See portfolio.py
